### ISSUE TITLE
Crash on my laptop QGIS 3.0.2 ubuntu 18.04LTS

### ISSUE THREAD

**Issue by guse92** [enricofer/go2mapillary#11]
Couldn't load plugin 'go2mapillary' due to an error when calling its classFactory() method ImportError: cannot import name 'QtWebKitWidgets' Traceback (most recent call last): File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin plugins[packageName] = package.classFactory(iface) File "/home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/__init__.py", line 40, in classFactory from .mapillary_explorer import go2mapillary File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import mod = _builtin_import(name, globals, locals, fromlist, level) File "/home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py", line 43, in from .mapillary_explorer_dockwidget import go2mapillaryDockWidget File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import mod = _builtin_import(name, globals, locals, fromlist, level) File "/home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer_dockwidget.py", line 28, in from .mapillary_explorer_dockwidget_base import Ui_go2mapillaryDockWidgetBase File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import mod = _builtin_import(name, globals, locals, fromlist, level) File "/home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer_dockwidget_base.py", line 55, in from PyQt5 import QtWebKitWidgets ImportError: cannot import name 'QtWebKitWidgets' Python version: 3.6.5 (default, Apr 1 2018, 05:46:30) [GCC 7.3.0] QGIS version: 3.0.2-Girona Girona, 307d082 Python Path: /usr/share/qgis/python /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins /usr/share/qgis/python/plugins /usr/lib/python36.zip /usr/lib/python3.6 /usr/lib/python3.6/lib-dynload /usr/local/lib/python3.6/dist-packages /usr/lib/python3/dist-packages /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/extlibs /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary /home/hermanguse/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary﻿

**Comment by enricofer** [comment]
from this: https://stackoverflow.com/questions/48848061/python-pyqt5-cannot-import-name-qwebview?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
appears that QtWebkitWidgets, needed for go2mapillary, are deprecated and removed from Qt5.6
but from this appears that they can be manually installed anyway
https://gis.stackexchange.com/questions/272459/how-to-install-qgis2web-in-qgis3-2-99-on-ubuntu-16-04

**Comment by rdandrimont** [comment]
I have the same error ;-)

Couldn't load plugin 'go2mapillary' due to an error when calling its
classFactory() method

ImportError: cannot import name 'QtWebKitWidgets'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/andrrap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/__init__.py",
line 40, in classFactory
    from .mapillary_explorer import go2mapillary
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/andrrap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer.py",
line 43, in
    from .mapillary_explorer_dockwidget import go2mapillaryDockWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/andrrap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer_dockwidget.py",
line 28, in
    from .mapillary_explorer_dockwidget_base import
Ui_go2mapillaryDockWidgetBase
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/andrrap/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2mapillary/mapillary_explorer_dockwidget_base.py",
line 55, in
    from PyQt5 import QtWebKitWidgets
ImportError: cannot import name 'QtWebKitWidgets'


Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
QGIS version: 3.0.2-Girona Girona, 307d082



Raphaël D'ANDRIMONT
*--*



2018-05-18 8:19 GMT+02:00 enrico ferreguti <notifications@github.com>:

**Comment by rdandrimont** [comment]
Indeed the sudo apt install python3-pyqt5.qtwebkit fix the problem, thanks!

Raphaël D'ANDRIMONT
*--*



2018-05-18 14:47 GMT+02:00 Raphaël d'Andrimont <raphael.dandrimont@gmail.com
