### ISSUE TITLE
not working on QGIS 3.4

### ISSUE THREAD

**Issue by iamnunocaldeira** [enricofer/go2mapillary#24]
Windows - 64bits ;)

**Comment by enricofer** [comment]
QGIS 3.4 has updated to GDAL 2.3.2 that doesn't read anymore MVT decoder output because of a wrong fature type assignment. I just file an issue: https://github.com/tilezen/mapbox-vector-tile/issues/107
Waiting for an official fix, I manually set it to "Feature" and everithing goes at it should be: https://github.com/enricofer/go2mapillary/commit/b95d98bca1a32896a2192e6e1b57bbebe8a19868
Thanks for submission
